// Generated by protocol/gen.py. Do not edit.
#pragma once
#include <cstdint>

namespace proto {
constexpr uint32_t kVersion = 1;
constexpr uint16_t kMagic = 0x5344;
constexpr uint32_t kHeaderSize = 20;
constexpr uint32_t kPenSampleSize = 35;
constexpr uint32_t kTouchSampleSize = 18;
constexpr uint32_t kVideoTrailerSize = 16;

namespace MsgType {
constexpr uint8_t NOP = 0;
constexpr uint8_t HELLO = 1;
constexpr uint8_t CONFIG = 2;
constexpr uint8_t VIDEO = 3;
constexpr uint8_t KEYFRAME_REQUEST = 4;
constexpr uint8_t PEN = 5;
constexpr uint8_t TOUCH = 6;
constexpr uint8_t PING = 7;
constexpr uint8_t PONG = 8;
constexpr uint8_t FRAME_STATS = 9;
constexpr uint8_t BYE = 10;
constexpr uint8_t DISPLAY_SIZE = 11;
}

namespace VideoFlag {
constexpr uint8_t KEYFRAME = 1;
constexpr uint8_t REFINEMENT = 2;
}

namespace Codec {
constexpr uint8_t HEVC = 0;
constexpr uint8_t H264 = 1;
}

namespace CodecMask {
constexpr uint8_t HEVC = 1;
constexpr uint8_t H264 = 2;
constexpr uint8_t HEVC_444 = 4;
}

namespace HelloFlag {
constexpr uint8_t LOW_LATENCY_DECODER = 1;
}

namespace HelloMsgFlag {
constexpr uint8_t REPLY = 1;
}

namespace KeyframeReason {
constexpr uint8_t STARTUP = 1;
constexpr uint8_t DECODER_ERROR = 2;
constexpr uint8_t SEQ_GAP = 3;
constexpr uint8_t USER = 4;
}

namespace PenPhase {
constexpr uint8_t HOVER = 0;
constexpr uint8_t DOWN = 1;
constexpr uint8_t MOVE = 2;
constexpr uint8_t UP = 3;
constexpr uint8_t PROXIMITY_IN = 4;
constexpr uint8_t PROXIMITY_OUT = 5;
}

namespace PenTool {
constexpr uint8_t PEN = 0;
constexpr uint8_t ERASER = 1;
}

namespace PenButton {
constexpr uint8_t PRIMARY = 1;
constexpr uint8_t SECONDARY = 2;
}

namespace TouchAction {
constexpr uint8_t DOWN = 0;
constexpr uint8_t MOVE = 1;
constexpr uint8_t UP = 2;
constexpr uint8_t CANCEL = 3;
}

namespace ByeReason {
constexpr uint8_t NORMAL = 0;
constexpr uint8_t ERROR = 1;
}
}  // namespace proto
