// Generated by protocol/gen.py. Do not edit.
package com.alexgwyn.tabdisplay

object Proto {
    const val VERSION = 1
    const val HEADER_SIZE = 20
    const val PEN_SAMPLE_SIZE = 35
    const val TOUCH_SAMPLE_SIZE = 18
    const val VIDEO_TRAILER_SIZE = 16
}

object MsgType {
    const val NOP = 0
    const val HELLO = 1
    const val CONFIG = 2
    const val VIDEO = 3
    const val KEYFRAME_REQUEST = 4
    const val PEN = 5
    const val TOUCH = 6
    const val PING = 7
    const val PONG = 8
    const val FRAME_STATS = 9
    const val BYE = 10
    const val DISPLAY_SIZE = 11
}

object VideoFlag {
    const val KEYFRAME = 1
    const val REFINEMENT = 2
}

object Codec {
    const val HEVC = 0
    const val H264 = 1
}

object CodecMask {
    const val HEVC = 1
    const val H264 = 2
    const val HEVC_444 = 4
}

object HelloFlag {
    const val LOW_LATENCY_DECODER = 1
}

object HelloMsgFlag {
    const val REPLY = 1
}

object KeyframeReason {
    const val STARTUP = 1
    const val DECODER_ERROR = 2
    const val SEQ_GAP = 3
    const val USER = 4
}

object PenPhase {
    const val HOVER = 0
    const val DOWN = 1
    const val MOVE = 2
    const val UP = 3
    const val PROXIMITY_IN = 4
    const val PROXIMITY_OUT = 5
}

object PenTool {
    const val PEN = 0
    const val ERASER = 1
}

object PenButton {
    const val PRIMARY = 1
    const val SECONDARY = 2
}

object TouchAction {
    const val DOWN = 0
    const val MOVE = 1
    const val UP = 2
    const val CANCEL = 3
}

object ByeReason {
    const val NORMAL = 0
    const val ERROR = 1
}
