#!/usr/bin/env python3
"""Single source of truth for wire-protocol constants. See spec.md for layouts.

Run: python3 protocol/gen.py   (writes Swift, C++ and Kotlin constant files)
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

VERSION = 1
MAGIC = 0x5344
HEADER_SIZE = 20

GROUPS = {
    "MsgType": [
        ("NOP", 0), ("HELLO", 1), ("CONFIG", 2), ("VIDEO", 3), ("KEYFRAME_REQUEST", 4),
        ("PEN", 5), ("TOUCH", 6), ("PING", 7), ("PONG", 8), ("FRAME_STATS", 9), ("BYE", 10),
        ("DISPLAY_SIZE", 11),
    ],
    "VideoFlag": [("KEYFRAME", 1), ("REFINEMENT", 2)],
    "Codec": [("HEVC", 0), ("H264", 1)],
    "CodecMask": [("HEVC", 1), ("H264", 2), ("HEVC_444", 4)],
    "HelloFlag": [("LOW_LATENCY_DECODER", 1)],
    "HelloMsgFlag": [("REPLY", 1)],  # header flags of a HELLO: answering another HELLO (don't answer it)
    "KeyframeReason": [("STARTUP", 1), ("DECODER_ERROR", 2), ("SEQ_GAP", 3), ("USER", 4)],
    "PenPhase": [("HOVER", 0), ("DOWN", 1), ("MOVE", 2), ("UP", 3), ("PROXIMITY_IN", 4), ("PROXIMITY_OUT", 5)],
    "PenTool": [("PEN", 0), ("ERASER", 1)],
    "PenButton": [("PRIMARY", 1), ("SECONDARY", 2)],
    "TouchAction": [("DOWN", 0), ("MOVE", 1), ("UP", 2), ("CANCEL", 3)],
    "ByeReason": [("NORMAL", 0), ("ERROR", 1)],
}

SIZES = [("PEN_SAMPLE_SIZE", 35), ("TOUCH_SAMPLE_SIZE", 18), ("VIDEO_TRAILER_SIZE", 16)]


def camel(name):
    parts = name.lower().split("_")
    return parts[0] + "".join(p.title() for p in parts[1:])


def swift():
    out = ["// Generated by protocol/gen.py. Do not edit.", "", "enum Proto {",
           f"    static let version: UInt32 = {VERSION}",
           f"    static let magic: UInt16 = 0x{MAGIC:04X}",
           f"    static let headerSize = {HEADER_SIZE}"]
    for n, v in SIZES:
        out.append(f"    static let {camel(n)} = {v}")
    out.append("}")
    for g, items in GROUPS.items():
        out += ["", f"enum {g} {{"] + [f"    static let {camel(n)}: UInt8 = {v}" for n, v in items] + ["}"]
    return "\n".join(out) + "\n"


def cpp():
    out = ["// Generated by protocol/gen.py. Do not edit.", "#pragma once", "#include <cstdint>", "", "namespace proto {",
           f"constexpr uint32_t kVersion = {VERSION};",
           f"constexpr uint16_t kMagic = 0x{MAGIC:04X};",
           f"constexpr uint32_t kHeaderSize = {HEADER_SIZE};"]
    for n, v in SIZES:
        out.append(f"constexpr uint32_t k{camel(n)[0].upper() + camel(n)[1:]} = {v};")
    for g, items in GROUPS.items():
        out += ["", f"namespace {g} {{"] + [f"constexpr uint8_t {n} = {v};" for n, v in items] + ["}"]
    out.append("}  // namespace proto")
    return "\n".join(out) + "\n"


def kotlin():
    out = ["// Generated by protocol/gen.py. Do not edit.", "package com.alexgwyn.tabdisplay", "", "object Proto {",
           f"    const val VERSION = {VERSION}",
           f"    const val HEADER_SIZE = {HEADER_SIZE}"]
    for n, v in SIZES:
        out.append(f"    const val {n} = {v}")
    out.append("}")
    for g, items in GROUPS.items():
        out += ["", f"object {g} {{"] + [f"    const val {n} = {v}" for n, v in items] + ["}"]
    return "\n".join(out) + "\n"


TARGETS = {
    "mac/Sources/TabDisplay/Protocol/ProtocolConstants.swift": swift,
    "android/app/src/main/cpp/protocol_constants.h": cpp,
    "android/app/src/main/java/com/alexgwyn/tabdisplay/ProtocolConstants.kt": kotlin,
}

if __name__ == "__main__":
    for rel, fn in TARGETS.items():
        p = ROOT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(fn())
        print("wrote", rel)
