// Generated by protocol/gen.py. Do not edit.

enum Proto {
    static let version: UInt32 = 1
    static let magic: UInt16 = 0x5344
    static let headerSize = 20
    static let penSampleSize = 35
    static let touchSampleSize = 18
    static let videoTrailerSize = 16
}

enum MsgType {
    static let nop: UInt8 = 0
    static let hello: UInt8 = 1
    static let config: UInt8 = 2
    static let video: UInt8 = 3
    static let keyframeRequest: UInt8 = 4
    static let pen: UInt8 = 5
    static let touch: UInt8 = 6
    static let ping: UInt8 = 7
    static let pong: UInt8 = 8
    static let frameStats: UInt8 = 9
    static let bye: UInt8 = 10
    static let displaySize: UInt8 = 11
}

enum VideoFlag {
    static let keyframe: UInt8 = 1
    static let refinement: UInt8 = 2
}

enum Codec {
    static let hevc: UInt8 = 0
    static let h264: UInt8 = 1
}

enum CodecMask {
    static let hevc: UInt8 = 1
    static let h264: UInt8 = 2
    static let hevc444: UInt8 = 4
}

enum HelloFlag {
    static let lowLatencyDecoder: UInt8 = 1
}

enum HelloMsgFlag {
    static let reply: UInt8 = 1
}

enum KeyframeReason {
    static let startup: UInt8 = 1
    static let decoderError: UInt8 = 2
    static let seqGap: UInt8 = 3
    static let user: UInt8 = 4
}

enum PenPhase {
    static let hover: UInt8 = 0
    static let down: UInt8 = 1
    static let move: UInt8 = 2
    static let up: UInt8 = 3
    static let proximityIn: UInt8 = 4
    static let proximityOut: UInt8 = 5
}

enum PenTool {
    static let pen: UInt8 = 0
    static let eraser: UInt8 = 1
}

enum PenButton {
    static let primary: UInt8 = 1
    static let secondary: UInt8 = 2
}

enum TouchAction {
    static let down: UInt8 = 0
    static let move: UInt8 = 1
    static let up: UInt8 = 2
    static let cancel: UInt8 = 3
}

enum ByeReason {
    static let normal: UInt8 = 0
    static let error: UInt8 = 1
}
